tasks:
  - init: |
      sudo apt install adb curl
      npm install --global http-server
    command: ./gitpod-adb init

ports:
  - port: 8080
    onOpen: ignore
  - port: 5555
    onOpen: ignore
  - port: 3000
    onOpen: open-browser
  - port: 5037
    onOpen: ignore
