tasks:
  - init: ./gitpod-adb init

image:
  file: Dockerfile

ports:
  - port: 8080
    onOpen: ignore
  - port: 5555
    onOpen: ignore
  - port: 3000
    onOpen: open-browser
  - port: 5037
    onOpen: ignore
